// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: grpcserver/proto/dns.proto

package dns

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X   string `protobuf:"bytes,1,opt,name=X,proto3" json:"X,omitempty"`
	Y   string `protobuf:"bytes,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z   string `protobuf:"bytes,3,opt,name=Z,proto3" json:"Z,omitempty"`
	Vel string `protobuf:"bytes,4,opt,name=Vel,proto3" json:"Vel,omitempty"`
}

func (x *LocationRequest) Reset() {
	*x = LocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcserver_proto_dns_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationRequest) ProtoMessage() {}

func (x *LocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcserver_proto_dns_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationRequest.ProtoReflect.Descriptor instead.
func (*LocationRequest) Descriptor() ([]byte, []int) {
	return file_grpcserver_proto_dns_proto_rawDescGZIP(), []int{0}
}

func (x *LocationRequest) GetX() string {
	if x != nil {
		return x.X
	}
	return ""
}

func (x *LocationRequest) GetY() string {
	if x != nil {
		return x.Y
	}
	return ""
}

func (x *LocationRequest) GetZ() string {
	if x != nil {
		return x.Z
	}
	return ""
}

func (x *LocationRequest) GetVel() string {
	if x != nil {
		return x.Vel
	}
	return ""
}

type LocationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Loc float64 `protobuf:"fixed64,1,opt,name=Loc,proto3" json:"Loc,omitempty"`
}

func (x *LocationResult) Reset() {
	*x = LocationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcserver_proto_dns_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationResult) ProtoMessage() {}

func (x *LocationResult) ProtoReflect() protoreflect.Message {
	mi := &file_grpcserver_proto_dns_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationResult.ProtoReflect.Descriptor instead.
func (*LocationResult) Descriptor() ([]byte, []int) {
	return file_grpcserver_proto_dns_proto_rawDescGZIP(), []int{1}
}

func (x *LocationResult) GetLoc() float64 {
	if x != nil {
		return x.Loc
	}
	return 0
}

var File_grpcserver_proto_dns_proto protoreflect.FileDescriptor

var file_grpcserver_proto_dns_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x64, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64, 0x6e,
	0x73, 0x22, 0x4d, 0x0a, 0x0f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x01, 0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x59,
	0x12, 0x0c, 0x0a, 0x01, 0x5a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x5a, 0x12, 0x10,
	0x0a, 0x03, 0x56, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x56, 0x65, 0x6c,
	0x22, 0x22, 0x0a, 0x0e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x6f, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x03, 0x4c, 0x6f, 0x63, 0x32, 0x51, 0x0a, 0x0d, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x2e, 0x64, 0x6e, 0x73,
	0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x64, 0x6e, 0x73, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x64, 0x6e, 0x73, 0x3b, 0x64, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcserver_proto_dns_proto_rawDescOnce sync.Once
	file_grpcserver_proto_dns_proto_rawDescData = file_grpcserver_proto_dns_proto_rawDesc
)

func file_grpcserver_proto_dns_proto_rawDescGZIP() []byte {
	file_grpcserver_proto_dns_proto_rawDescOnce.Do(func() {
		file_grpcserver_proto_dns_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcserver_proto_dns_proto_rawDescData)
	})
	return file_grpcserver_proto_dns_proto_rawDescData
}

var file_grpcserver_proto_dns_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcserver_proto_dns_proto_goTypes = []interface{}{
	(*LocationRequest)(nil), // 0: dns.LocationRequest
	(*LocationResult)(nil),  // 1: dns.LocationResult
}
var file_grpcserver_proto_dns_proto_depIdxs = []int32{
	0, // 0: dns.SectorService.CalculateLocation:input_type -> dns.LocationRequest
	1, // 1: dns.SectorService.CalculateLocation:output_type -> dns.LocationResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcserver_proto_dns_proto_init() }
func file_grpcserver_proto_dns_proto_init() {
	if File_grpcserver_proto_dns_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcserver_proto_dns_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcserver_proto_dns_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcserver_proto_dns_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcserver_proto_dns_proto_goTypes,
		DependencyIndexes: file_grpcserver_proto_dns_proto_depIdxs,
		MessageInfos:      file_grpcserver_proto_dns_proto_msgTypes,
	}.Build()
	File_grpcserver_proto_dns_proto = out.File
	file_grpcserver_proto_dns_proto_rawDesc = nil
	file_grpcserver_proto_dns_proto_goTypes = nil
	file_grpcserver_proto_dns_proto_depIdxs = nil
}
