// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: grpcserver/proto/dns.proto

package dns

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SectorServiceClient is the client API for SectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SectorServiceClient interface {
	CalculateLocation(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationResult, error)
}

type sectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSectorServiceClient(cc grpc.ClientConnInterface) SectorServiceClient {
	return &sectorServiceClient{cc}
}

func (c *sectorServiceClient) CalculateLocation(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationResult, error) {
	out := new(LocationResult)
	err := c.cc.Invoke(ctx, "/dns.SectorService/CalculateLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SectorServiceServer is the server API for SectorService service.
// All implementations must embed UnimplementedSectorServiceServer
// for forward compatibility
type SectorServiceServer interface {
	CalculateLocation(context.Context, *LocationRequest) (*LocationResult, error)
	mustEmbedUnimplementedSectorServiceServer()
}

// UnimplementedSectorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSectorServiceServer struct {
}

func (UnimplementedSectorServiceServer) CalculateLocation(context.Context, *LocationRequest) (*LocationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateLocation not implemented")
}
func (UnimplementedSectorServiceServer) mustEmbedUnimplementedSectorServiceServer() {}

// UnsafeSectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SectorServiceServer will
// result in compilation errors.
type UnsafeSectorServiceServer interface {
	mustEmbedUnimplementedSectorServiceServer()
}

func RegisterSectorServiceServer(s grpc.ServiceRegistrar, srv SectorServiceServer) {
	s.RegisterService(&SectorService_ServiceDesc, srv)
}

func _SectorService_CalculateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SectorServiceServer).CalculateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dns.SectorService/CalculateLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SectorServiceServer).CalculateLocation(ctx, req.(*LocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SectorService_ServiceDesc is the grpc.ServiceDesc for SectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dns.SectorService",
	HandlerType: (*SectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateLocation",
			Handler:    _SectorService_CalculateLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcserver/proto/dns.proto",
}
